// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0ZUxMl7DTRQK--nzwjxehz6qZuTqNarw',
    appId: '1:284674831094:web:44fee14e202031043a32d7',
    messagingSenderId: '284674831094',
    projectId: 'news-world-elfoly',
    authDomain: 'news-world-elfoly.firebaseapp.com',
    storageBucket: 'news-world-elfoly.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpuubi6xyV5MCmO2zcUIbrn3nZHUzXkRg',
    appId: '1:331072748748:android:f8799bf9c0c31f4565d669',
    messagingSenderId: '331072748748',
    projectId: 'news-wave-25595',
    storageBucket: 'news-wave-25595.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUS1wNOaUS4uJEwH6kqcapzyL28OFKWBw',
    appId: '1:331072748748:ios:e63d4f71591eceb265d669',
    messagingSenderId: '331072748748',
    projectId: 'news-wave-25595',
    storageBucket: 'news-wave-25595.appspot.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzX8HERm3VOevK7MKP9EL2fz9ACv6faWM',
    appId: '1:284674831094:ios:c203e815c4cc9b983a32d7',
    messagingSenderId: '284674831094',
    projectId: 'news-world-elfoly',
    storageBucket: 'news-world-elfoly.appspot.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0ZUxMl7DTRQK--nzwjxehz6qZuTqNarw',
    appId: '1:284674831094:web:6d2c51771d1c48593a32d7',
    messagingSenderId: '284674831094',
    projectId: 'news-world-elfoly',
    authDomain: 'news-world-elfoly.firebaseapp.com',
    storageBucket: 'news-world-elfoly.appspot.com',
  );
}